# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: Jonbin's Website
  params:
    description: 陈健斌
  menu:
    main:
      - name: 个人简介
        url: '#about'
        weight: 1
      - name: 项目
        url: '#projects'
        weight: 2
      - name: 经历
        url: '#experience'
        weight: 3
      - name: 技能
        url: '#skills'
        weight: 4
      - name: 荣誉
        url: '#accomplishments'
        weight: 5
      - name: 联系方式
        url: '#contact'
        weight: 6 